In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\Datascience_internship.zip\dataset\Dataset .csv")

In [10]:
cuisine_rating = (
    df.groupby('Cuisines')['Aggregate rating']
      .mean()
      .reset_index()
      .sort_values('Aggregate rating', ascending=False)
)

cuisine_rating.head(10)

                             Cuisines  Aggregate rating
302           Burger, Bar Food, Steak               4.9
33            American, Burger, Grill               4.9
37       American, Caribbean, Seafood               4.9
41           American, Coffee and Tea               4.9
1214  Mexican, American, Healthy Food               4.9
1034     Italian, Bakery, Continental               4.9
169          BBQ, Breakfast, Southern               4.9
808                  European, German               4.9
949                 Hawaiian, Seafood               4.9
1779                Sunda, Indonesian               4.9

In [13]:
df.groupby('Cuisines')['Votes'].mean().sort_values(ascending=False).head(10).reset_index()

                                            Cuisines         Votes
0                           Italian, American, Pizza  10934.000000
1                             American, Burger, Cafe   9667.000000
2  Finger Food, North Indian, Italian, Continenta...   5705.000000
3  American, Continental, Italian, North Indian, ...   4914.000000
4              European, Mediterranean, North Indian   4180.333333
5  Cafe, Mexican, American, Italian, Lebanese, Co...   4085.000000
6            American, North Indian, European, Asian   3697.000000
7    North Indian, Mediterranean, Asian, Continental   3413.000000
8                          American, Desserts, Steak   3157.000000
9                                 Desserts, Bar Food   3074.000000

In [15]:
df.groupby('Cuisines')['Aggregate rating'].mean().sort_values(ascending=False).head(10)

Cuisines
Burger, Bar Food, Steak            4.9
American, Burger, Grill            4.9
American, Caribbean, Seafood       4.9
American, Coffee and Tea           4.9
Mexican, American, Healthy Food    4.9
Italian, Bakery, Continental       4.9
BBQ, Breakfast, Southern           4.9
European, German                   4.9
Hawaiian, Seafood                  4.9
Sunda, Indonesian                  4.9
Name: Aggregate rating, dtype: float64